# Generated by Django 3.2.3 on 2021-06-10 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='user_id',
        ),
        migrations.AddField(
            model_name='notifications',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
