# Generated by Django 3.2.3 on 2021-06-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210610_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
